name: Refresh Activity Badge

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes (tune as you like)
  workflow_dispatch:

jobs:
  badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install pillow requests

      - name: Update logo badge
        env:
          VISITS_API: "https://biblebucket.com/api/visits"
        run: |
          python - << 'PY'
          import os, json, requests
          from PIL import Image, ImageDraw, ImageFont

          API = os.environ["VISITS_API"]
          r = requests.get(API, timeout=10)
          total = r.json().get("total", 0)

          LOGO_IN  = "assets/logo_base.png"  # your clean original
          LOGO_OUT = "assets/logo.png"

          img = Image.open(LOGO_IN).convert("RGBA")
          w,h = img.size

          badge_text = f"{total:,}"
          pad = max(8, w//100)
          bh = max(28, w//16)
          bw = max(60, 24 + 16*len(badge_text))

          badge = Image.new("RGBA", (bw, bh), (0,0,0,0))
          d = ImageDraw.Draw(badge)
          d.rounded_rectangle([0,0,bw,bh], radius=bh//2, fill=(11,37,71,230))  # BB navy w/ alpha

          try:
            font = ImageFont.truetype("assets/Inter-SemiBold.ttf", size=bh - pad*2)
          except:
            font = ImageFont.load_default()

          tw, th = d.textbbox((0,0), badge_text, font=font)[2:]
          d.text(((bw-tw)//2, (bh-th)//2), badge_text, font=font, fill=(255,255,255,255))

          img.alpha_composite(badge, dest=(w - bw - pad, pad))
          img.save(LOGO_OUT, optimize=True)
          print("Updated logo.png with total:", total)
          PY

      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add assets/logo.png
          git commit -m "chore: update activity badge" || echo "No changes"
          git push
